"""empty message

Revision ID: c6089286c7cb
Revises: f0bdd64717d3
Create Date: 2020-03-30 15:36:46.310853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6089286c7cb'
down_revision = 'f0bdd64717d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addsizes')
    op.drop_index('name', table_name='sizes')
    op.drop_table('sizes')
    op.drop_index('name', table_name='products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'products', ['name'], unique=True)
    op.create_table('sizes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'sizes', ['name'], unique=True)
    op.create_table('addsizes',
    sa.Column('size_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='addsizes_ibfk_1'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='addsizes_ibfk_2'),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
