"""Add textual to model Product

Revision ID: f0bdd64717d3
Revises: d8527a0fa694
Create Date: 2020-03-29 15:38:18.015869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bdd64717d3'
down_revision = 'd8527a0fa694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('textual', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'textual')
    # ### end Alembic commands ###
